Repository CirclesUBI/circles-api, pull requests merged in 2021-03, with the labels that each got.

#50 Add github actions script. Test
  .github/workflows/run-tests.yml
  .nvmrc
  .travis.yml
  README.md
Labels: CI :ice_skate:

#24 Scheduler and worker
  .env.example
  README.md
  package-lock.json
  package.json
  src/constants.js
  src/controllers/transfers.js
  src/index.js
  src/models/edges.js
  src/services/edgesDatabase.js
  src/services/edgesFile.js
  src/services/edgesFromEvents.js
  src/services/edgesFromGraph.js
  src/services/edgesGraph.js
  src/services/edgesUpdate.js
  src/services/findTransferSteps.js
  src/services/graph.js
  src/services/redis.js
  src/tasks/cleanup.js
  src/tasks/exportEdges.js
  src/tasks/index.js
  src/tasks/processor.js
  src/tasks/submitJob.js
  src/tasks/syncAddress.js
  src/tasks/syncFullGraph.js
  src/tasks/uploadEdgesS3.js
  src/worker.js
  test/transfers-find-edges.test.js
  test/transfers-find-steps.test.js
  test/utils/mocks.js
Labels: enhancement :sparkler:, priority ★★★, refactor :bee:

#58 Change pathfinder and edges.json file paths
  src/constants.js
  src/services/edgesFile.js
Labels: refactor :bee:

#61 Subscribe again to Ethereum events when connection got dropped
  src/services/web3.js
Labels: bug :boom:
